'use client'
import { useEffect, useMemo, useState } from 'react'
import dynamic from 'next/dynamic'
import useSWR from 'swr'
import { Activity, ArrowDownLeft, ArrowUpRight, ChartCandlestick, Check, ChevronDown, CircleHelp, Crosshair, ExternalLink, Layers, LockKeyhole, Maximize2, Radio, RefreshCw, ShieldCheck, SlidersHorizontal, Wifi, Zap } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { useMarket, fetcher } from '@/hooks/use-market'
import { analyze, fmt, type Candle, type Setup } from '@/lib/market'
const PriceChart = dynamic(()=>import('./price-chart').then(m=>m.PriceChart),{ssr:false,loading:()=> <div className="price-chart chart-empty">Initializing chart engine…</div>})
const empty: Candle[]=[]
function PanelTitle({icon:Icon,title,right}:{icon:typeof Activity;title:string;right?:React.ReactNode}){return <div className="panel-heading"><h2><Icon size={14}/>{title}</h2>{right}</div>}
function Row({label,value,tone=''}:{label:string;value:React.ReactNode;tone?:string}){return <div className="metric-row"><span>{label}</span><strong className={tone}>{value}</strong></div>}
function Ticket({setup,ready,score,entryReady}:{setup:Setup|null;ready:boolean;score:number|undefined;entryReady:boolean}){
  return <section className="panel ticket"><PanelTitle icon={Crosshair} title="Precision signal" right={<span className="micro-tag">1M SCALP</span>}/><div className="ticket-content">
    <div className="eyebrow">CONFIRMED-CANDLE SETUP</div><div className={`direction ${ready&&setup ? setup.direction==='LONG'?'positive':'negative':'gold'}`}>{ready&&setup ? <>{setup.direction==='LONG'?<ArrowUpRight/>:<ArrowDownLeft/>}{setup.direction}</>:<><Radio/>STAND BY</>}<span className="signal-label">{ready&&setup?(entryReady?'IN ENTRY ZONE':'WATCH ONLY'):!ready?'SAFETY GATE':'SCANNING'}</span></div>
    <div className="score-heading"><span>Rule alignment <CircleHelp size={12}/></span><b>{score==null?'—':`${score}%`} <small>/ 100</small></b></div><div className="score-track"><div style={{width:`${score??0}%`}}/></div><p className="fine-print">Rule agreement, not a win probability.</p>
    <div className="entry-box"><span>CALCULATED ENTRY <Crosshair size={13}/></span><strong>{ready&&setup?fmt(setup.entry):'—'}<small> USDT</small></strong><div>Closed-candle reference · not a guaranteed fill</div></div>
    <Row label="Stop loss" value={ready&&setup?fmt(setup.stop):'—'} tone="negative"/><Row label="Take profit" value={ready&&setup?fmt(setup.target):'—'} tone="positive"/><Row label="Risk / reward · gross" value={ready&&setup?'1 : 2.00':'—'}/><Row label="Setup lifetime" value="≤ 12 min"/><Row label="Execution" value="Analysis only"/>
    <div className="lock-note"><LockKeyhole size={14}/><span>Fixed entry. Fixed invalidation.<br/><strong>No intrabar direction switching.</strong></span></div>
  </div></section>
}
export function Terminal(){
  const m=useMarket(), [interval,setInterval]=useState('1m'),[view,setView]=useState('Terminal'),[showLevels,setShowLevels]=useState(true),[showBook,setShowBook]=useState(true),[details,setDetails]=useState(false)
  const other=useSWR<{candles:Candle[]}>(interval==='1m'?null:`/api/market?kind=candles&bar=${interval}`,fetcher,{refreshInterval:10000,errorRetryInterval:15000})
  const candles=m.candles.data?.candles??empty
  const analysis=useMemo(()=>analyze(candles,m.instrument.data?.tick),[candles,m.instrument.data?.tick])
  const ind=analysis.current,t=m.ticker,book=m.book,meta=m.instrument.data
  const closedAge=analysis.lastClosed&&m.now?m.now/1000-analysis.lastClosed:Infinity
  const continuous=candles.filter(c=>c.closed).slice(-51).every((c,i,a)=>i===0||c.time-a[i-1].time===60)
  const ready=m.fresh&&closedAge>=60&&closedAge<125&&continuous&&!m.candles.error
  const active=analysis.active
  const [invalidatedId,setInvalidatedId]=useState<number|null>(null)
  const touched=!!active&&!!t&&(active.direction==='LONG'?(t.bid<=active.stop||t.bid>=active.target):(t.ask>=active.stop||t.ask<=active.target))
  useEffect(()=>{if(touched&&active)setInvalidatedId(active.id)},[touched,active])
  const expired=!!active&&(m.now/1000-active.id>=12*60||Math.floor(m.now/1000/900)!==Math.floor(active.id/900))
  const breached=touched||!!active&&invalidatedId===active.id||expired
  const spreadOK=!!t&&!!ind&&t.ask-t.bid<=ind.atr*.2
  const nearEntry=!!t&&!!ind&&!!active&&Math.abs((active.direction==='LONG'?t.ask:t.bid)-active.entry)<=ind.atr*.35
  const usable=ready&&!breached&&spreadOK&&nearEntry
  const change=t?(t.last/t.open-1)*100:null
  const shown=interval==='1m'?candles:other.data?.candles??empty
  const score=ind?Math.max(ind.long,ind.short):undefined
  const totalBid=book?.bids.reduce((s,x)=>s+x[1],0)??0,totalAsk=book?.asks.reduce((s,x)=>s+x[1],0)??0
  const bidShare=totalBid+totalAsk>0?totalBid/(totalBid+totalAsk)*100:null
  const status=!m.now?'CONNECTING':m.fresh?'LIVE MARKET':'FEED DELAYED'
  const clock=m.now?new Date(m.now).toISOString().slice(11,19):'--:--:--'
  function exportData(){const b=new Blob([JSON.stringify({source:'OKX XAU-USDT-SWAP',snapshot:m.snapshot.data,candles,analysis,exportedAt:new Date().toISOString()},null,2)],{type:'application/json'});const u=URL.createObjectURL(b);const a=document.createElement('a');a.href=u;a.download='xau-market-snapshot.json';a.click();URL.revokeObjectURL(u)}
  return <div className="terminal-shell">
    <header className="topbar"><a className="brand" href="/"><span className="brand-mark"><ChartCandlestick size={23}/></span><span>AURUM<span className="brand-sub">TERMINAL</span></span><span className="version">PRO</span></a><nav aria-label="Main navigation">{['Terminal','Data sources','Methodology'].map(v=><button key={v} onClick={()=>setView(v)} className={view===v?'nav-active':''}>{v}</button>)}</nav><div className="header-status"><span className={`status-dot ${m.fresh?'live':''}`}/>{status}</div><div className="clock">{clock}<span> UTC</span></div><Button variant="ghost" size="icon-sm" onClick={()=>setDetails(!details)} aria-label="Toggle terminal information"><CircleHelp/></Button></header>
    <main>
      <div className="page-heading"><div><div className="breadcrumb">MARKETS <span>/</span> PRECIOUS METALS <span>/</span> <b>GOLD</b></div><h1>XAU / USDT <span>PERPETUAL</span><span className="exchange-tag">OKX <ChevronDown size={11}/></span></h1></div><div className="page-actions"><span className="verified"><ShieldCheck size={14}/>{meta?'Verified XAU contract':'Verifying XAU contract'}</span><Button variant="outline" size="sm" onClick={m.refresh}><RefreshCw data-icon="inline-start"/>Refresh</Button><Button variant="outline" size="sm" onClick={()=>setShowBook(!showBook)}><SlidersHorizontal data-icon="inline-start"/>Layout</Button></div></div>
      <section className="ticker-strip" aria-label="Market statistics"><div className="last-price"><span className="stat-label">LAST TRADED PRICE</span><div>{fmt(t?.last)}<span className={(change??0)>=0?'positive':'negative'}>{change==null?'—':`${change>=0?'+':''}${fmt(change)}%`}</span></div></div>{[['24H HIGH',fmt(t?.high)],['24H LOW',fmt(t?.low)],['24H VOLUME · XAU',fmt(t?.volume,1)],['BID / ASK',`${fmt(t?.bid)} / ${fmt(t?.ask)}`],['SPREAD · USDT',t?fmt(t.ask-t.bid):'—'],['FUNDING RATE',meta?.funding==null?'—':`${fmt(meta.funding*100,4)}%`]].map(([label,value])=><div className="ticker-stat" key={label}><span className="stat-label">{label}</span><strong>{value}</strong></div>)}</section>
      {(details||view==='Methodology')&&<section className="info-panel"><h2>Transparent calculations. No certainty claims.</h2><p>Signals use only closed 1-minute OKX candles: SMA 9/21 (30 points), close vs SMA 50 (25), simple RSI 14 (20), and rolling VWAP 20 (25). Two consecutive candles must agree at 75+ points. Entry is the confirming close rounded to the exchange tick. Stop uses the wider of 1.2 × average true range (14) and the five-candle extreme; target is twice that risk. Levels do not move with live price.</p><p>A setup ends at its stop, target, after 12 minutes, or the next UTC 15-minute boundary; a cooldown prevents immediate reversal. Live display additionally requires spread ≤ 0.2 ATR and executable quote distance from entry ≤ 0.35 ATR. A touched level stays blocked for that setup during this session. These are hypothetical watch levels, not orders or verified fills. Fees, slippage and funding reduce returns. No backtested success probability is claimed. More confirmation necessarily misses some opportunities.</p><a href="https://www.okx.com/docs-v5/en/" target="_blank" rel="noreferrer">OKX API documentation <ExternalLink size={12}/></a></section>}
      {view==='Data sources'?<section className="panel sources-page"><PanelTitle icon={Wifi} title="Exchange access research" right={<span className="micro-tag">XAU ONLY</span>}/><div className="source-grid">{[['OKX','XAU-USDT-SWAP','Selected · REST + WebSocket','Ticker probes: 270 / 161 / 166 ms'],['MEXC','XAU_USDT','Exact contract verified','Ticker probes: 596 / 41 / 40 ms'],['Gate','XAU_USDT','Exact contract verified','Ticker probes: 563 / 552 / 144 ms'],['Binance','XAUUSDT','HTTP 451 from this region','Three requests blocked; no speed ranking']].map(([name,symbol,state,note])=><article key={name}><h3>{name}</h3><strong>{symbol}</strong><p>{state}</p><small>{note}</small></article>)}</div><p className="source-caveat">Measured 18 Sep 2026, 10:50 UTC from this server; three REST ticker requests per venue. MEXC had the lowest median (41 ms), versus OKX (166 ms) and Gate (552 ms). This is not a streaming latency or universal speed ranking. OKX is selected as requested. Latency depends on region, route and market activity. No restriction bypass, synthetic feed, PAXG or XAUT substitution. OKX server snapshot round trip: {fmt(m.snapshot.data?.latency,0)} ms.</p><Button variant="outline" onClick={exportData}>Export current raw snapshot</Button></section>:<>
      <div className={`workspace ${!showBook?'without-book':''}`}>
        <section className="panel chart-panel"><PanelTitle icon={ChartCandlestick} title="Price action" right={<span className="chart-source"><span className={`status-dot ${m.fresh?'live':''}`}/>OKX · XAU-USDT-SWAP</span>}/><div className="chart-toolbar"><div className="timeframes" role="group" aria-label="Chart timeframe">{['1m','3m','5m','15m','1H'].map(tf=><button key={tf} aria-pressed={interval===tf} onClick={()=>setInterval(tf)} className={interval===tf?'selected':''}>{tf.toLowerCase()}</button>)}</div><span className="toolbar-divider"/><button className={`tool-label ${showLevels?'gold':''}`} onClick={()=>setShowLevels(!showLevels)} aria-pressed={showLevels}><Layers size={13}/>Setup levels</button><span className="chart-legend"><i/>SMA 21</span><button className="fullscreen" aria-label="Expand chart" onClick={()=>{const el=document.querySelector('.chart-panel');if(document.fullscreenElement)void document.exitFullscreen();else void el?.requestFullscreen()}}><Maximize2 size={14}/></button></div><div className="chart-meta">XAUUSDT <span>· {interval} · OKX</span><b className="positive">{fmt(t?.last)}</b><span className="chart-caption">VOLUME IN XAU</span></div>{shown.length?<PriceChart candles={shown} setup={showLevels&&ready&&!breached?active:null} interval={interval}/>:<div className="price-chart chart-empty"><Radio size={28}/><strong>{(interval==='1m'?m.candles.error:other.error)?'Market candles unavailable':'Connecting to live OKX candles'}</strong><span>No simulated chart data is used.</span></div>}<div className="chart-footer"><span><span className={`status-dot ${m.fresh?'live':''}`}/>{m.connected?'WebSocket + REST recovery':'REST recovery · streaming reconnects'}</span><span>Chart: {interval} <b>·</b> Signal engine: 1m <b>·</b> UTC</span></div></section>
        {showBook&&<section className="panel orderbook"><PanelTitle icon={Layers} title="Order book" right={<span className="micro-tag">L2</span>}/><div className="book-subtitle"><span>PRICE (USDT)</span><span>SIZE (CONTRACTS)</span></div><div className="book-rows">{book?.asks.slice(0,7).reverse().map(([p,q])=><div className="book-row ask" key={p}><i style={{width:`${q/Math.max(...book.asks.map(x=>x[1]))*100}%`}}/><span>{fmt(p)}</span><b>{fmt(q,0)}</b></div>)??<p className="empty-copy">Waiting for verified depth</p>}</div><div className="book-mid"><strong>{fmt(t?.last)} <span>↔</span></strong><small>Spread {t?fmt(t.ask-t.bid):'—'}</small></div><div className="book-rows">{book?.bids.slice(0,7).map(([p,q])=><div className="book-row bid" key={p}><i style={{width:`${q/Math.max(...book.bids.map(x=>x[1]))*100}%`}}/><span>{fmt(p)}</span><b>{fmt(q,0)}</b></div>)}</div><div className="book-balance"><div><span className="positive">B {fmt(bidShare,1)}%</span><span className="negative">S {bidShare==null?'—':fmt(100-bidShare,1)}%</span></div><div className="balance-bar"><i style={{width:`${bidShare??0}%`}}/></div><small>Displayed depth · {m.fresh?'fresh':'check data age'}</small></div></section>}
        <Ticket setup={active} ready={ready&&!breached} score={active?.score??score} entryReady={usable}/>
      </div>
      <div className="analysis-grid"><section className="panel consensus"><PanelTitle icon={Activity} title="Directional confluence" right={<span className="micro-tag">4 TRANSPARENT RULES</span>}/><div className="dual-scores"><div><span><ArrowUpRight size={13}/> LONG ALIGNMENT</span><strong className="positive">{ind?ind.long:'—'}<small>%</small></strong><div className="alignment-track"><i style={{width:`${ind?.long??0}%`}}/></div></div><div><span><ArrowDownLeft size={13}/> SHORT ALIGNMENT</span><strong className="negative">{ind?ind.short:'—'}<small>%</small></strong><div className="alignment-track short"><i style={{width:`${ind?.short??0}%`}}/></div></div></div><div className="factors">{ind?.factors.map(f=><div key={f.name}><span>{f.name}<small>{f.detail}</small></span><span className={f.long?'positive':f.short?'negative':'muted'}>{f.long?'BULLISH':f.short?'BEARISH':'NEUTRAL'}</span><b>{f.weight}<small> pts</small></b></div>)??<p className="empty-copy">Awaiting sufficient closed candles.</p>}</div></section>
      <section className="panel indicators"><PanelTitle icon={ChartCandlestick} title="Indicator engine" right={<span className="micro-tag">CLOSED 1M</span>}/><div className="indicator-grid">{[['RSI (14)',ind?.rsi,'Momentum'],['ATR (14)',ind?.atr,'Volatility · USDT'],['SMA (9)',ind?.fast,'Fast trend'],['SMA (21)',ind?.slow,'Slow trend'],['VWAP (20)',ind?.vwap,'Volume-weighted'],['SMA (50)',ind?.trend,'Trend filter']].map(([name,val,sub])=><div key={String(name)}><span>{name}</span><strong>{fmt(val as number|undefined)}</strong><small>{sub}</small></div>)}</div></section>
      <section className="panel safeguards"><PanelTitle icon={ShieldCheck} title="Signal safeguards" right={<LockKeyhole size={13} className="gold"/>}/><div className="safeguard-list">{[['Exact XAU instrument',!!meta],['Live price + depth',m.fresh],['Closed candles + continuity',closedAge>=60&&closedAge<125&&continuous&&!m.candles.error],['Two-candle confirmation',!!active],['Spread / entry distance',spreadOK&&nearEntry],['Price within setup bounds',!!active&&!breached]].map(([name,pass])=><div key={String(name)}><span className={pass?'positive':'muted'}>{pass?<Check size={14}/>:<span className="gate-pending"/>}</span><span>{name}</span><small className={pass?'positive':'muted'}>{pass?'PASS':'WAIT'}</small></div>)}</div><div className={`gate-status ${usable&&active?'positive':'gold'}`}><ShieldCheck size={14}/>{usable&&active?'Setup available for review':breached?'Level touched · setup blocked':'Protecting capital. Waiting for confirmation.'}</div></section></div>
      <div className="bottom-grid"><section className="panel history"><PanelTitle icon={Crosshair} title="Recent calculated setups" right={<span className="muted">Reconstructed · not executed trades</span>}/><div className="table-scroll"><table><thead><tr><th>TIME (UTC)</th><th>DIRECTION</th><th>ENTRY</th><th>STOP LOSS</th><th>TARGET</th><th>STATUS</th></tr></thead><tbody>{analysis.history.slice(0,4).map(s=><tr key={s.id}><td>{new Date(s.id*1000).toISOString().slice(11,16)}</td><td className={s.direction==='LONG'?'positive':'negative'}>{s.direction==='LONG'?'↗':'↙'} {s.direction}</td><td>{fmt(s.entry)}</td><td>{fmt(s.stop)}</td><td>{fmt(s.target)}</td><td><span className="history-status">{s.status}</span></td></tr>)}</tbody></table>{!analysis.history.length&&<p className="empty-copy">No confirmed setups in the loaded candle window.</p>}</div></section><section className="panel tape"><PanelTitle icon={Zap} title="Recent trades" right={<span className="micro-tag">EXCHANGE TAPE</span>}/><div className="trade-head"><span>PRICE</span><span>CONTRACTS</span><span>UTC</span></div>{m.snapshot.data?.trades.slice(0,4).map(tr=><div className="trade-row" key={tr.id}><span className={tr.side==='buy'?'positive':'negative'}>{fmt(tr.price)}</span><span>{fmt(tr.size,0)}</span><span>{new Date(tr.ts).toISOString().slice(11,19)}</span></div>)??<p className="empty-copy">Waiting for exchange trades.</p>}</section></div>
      </>}
      <div className="risk-disclaimer"><ShieldCheck size={13}/><p>Real market data. No guaranteed outcomes. Setup scores are not win probabilities. Entry levels do not guarantee fills; fees and slippage are not included. Trading can result in substantial losses.</p><a href="https://www.okx.com/trade-swap/xau-usdt-swap" target="_blank" rel="noreferrer">View on OKX <ExternalLink size={12}/></a></div>
    </main><footer className="statusbar"><div><span className={`status-dot ${m.fresh?'live':''}`}/><span>{m.fresh?'Market data connected':'Awaiting fresh market data'}</span><i/><span>OKX PUBLIC API</span><i/><span>REST {fmt(m.snapshot.data?.latency,0)} ms</span></div><div><span>PRICE AGE {Number.isFinite(m.age)?`${(m.age/1000).toFixed(1)}s`:'—'}</span><i/><span className="gold"><ShieldCheck size={11}/>NO SYNTHETIC DATA</span><i/><span>ENGINE v1.0</span></div></footer>
  </div>
}
